# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Maypole-Plugin-Authentication-UserSessionCookie
version:      1.5
version_from: UserSessionCookie.pm
installdirs:  site
requires:
    Maypole:                       2.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
